# Exported from Render on 2024-09-05T10:43:05Z
services:
- type: web
  name: boma
  runtime: docker
  repo: https://github.com/alex-mbolonzi/openkoda-docker
  plan: free
  envVars:
  - key: PORT
    value: 8080
  - key: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://dpg-crcotdij1k6c73cqh86g-a/openkoda_3lit
  - key: SPRING_DATASOURCE_USERNAME
    value: openkoda_3lit_user
  - key: SPRING_DATASOURCE_PASSWORD
    value: JM1iJCVG6eW71jujez814fHVuzu3yW1c
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: .
  healthCheckPath: /
version: "1"

databases:
  - name: openkoda # A PostgreSQL database named django-app-db running on a free instance
    plan: free
