# Exported from Render on 2024-09-05T10:43:05Z
services:
- type: web
  name: boma
  runtime: docker
  repo: https://github.com/alex-mbolonzi/openkoda-docker
  plan: free
  envVars:
  - key: PORT
    fromDatabase:
          name: openkoda
          property: connectionString
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: .
version: "1"

databases:
  - name: openkoda # A PostgreSQL database named django-app-db running on a free instance
    plan: free
